### PR TITLE
Added new Agent AI-Business-Insider in ai_agent_tutorials

### PR DESCRIPTION
**Pull request by Madhuvod**
**Description**: This project is a News Engine that helps users research a news topic, fact-check information, summarise key findings, and analyze trends to help find their Potential Business Ideas for their own Company! It leverages multiple AI agents to collect, verify, and analyze news, enabling users to extract insights and identify key opportunities across various news articles. The application uses CrewAI to orchestrate these tasks and provide an interactive experience.

**Problem Statement**: This is quite Personal to me, since my 1st year of Uni, I always wanted to be an Entreprenuer. Back then, I was constantly looking for a gap in the market, a problem that I can solve by constantly by reading news articles extensively, which was a very hard task. So now, we build this :)

Frontend: Streamlit
Backend:
Python (with FastAPI for the API backend)
AI/ML Tools:
CrewAI for orchestrating AI agents
Google Fact-Check Tools API
OpenAI for trend analysis
Web Scraping: Custom web scrapers and external APIs (News API)

Screenshot 2024-11-06 at 4 03 04 AM

Screenshot 2024-11-06 at 4 02 46 AM

### CODE REVIEW

**Comment by Shubhamsaboo** [comment]
Great choice and combination of tools. 
But, can you give me a more concrete and real world example of what do I use this application for?

**Comment by Madhuvod** [comment]
> Great choice and combination of tools. But, can you give me a more concrete and real world example of what do I use this application for?

Thanks for that!

One liner: An AI-powered news aggregator that simplifies access to recent, sector-specific news and trends, helping users stay informed and spot business opportunities effortlessly.

Basic Idea: Mainstream News and Media is very clustered and time taking to go through multiple news domains at a time. With the help of this application integrated with a LLM, people can study and read about the recent news updates easily of a particular sector they are interested in, across multiple news articles instantly - also giving them what the trends are. 

Sometimes people want to read about sports, finance and business, the tech industry and even the Politics in depth - this application helps them to query the sector they want to the recent news about, and they get it along with the potential business opportunities that are there, helping them in their entrepreneurial journey too! If they find any particular article interesting, they can click the link of that particular article directly.

My initial thought was this can even be a potential business idea too (this is still a demo version tho)

**Comment by Madhuvod** [comment]
@Shubhamsaboo can you please let me know what you think about this project? It's quite an advanced agent workflow -  I'll be also adding a Voice of the final Agent using the Sarvam's Voice API and deploy it soon on render. Would love your feedback as I can't miss any opportunity to work under you even for an internship :)

**Comment by Shubhamsaboo** [comment]
@Madhuvod sorry for the delayed response. A lot is happening these days! 

Your project looks awesome. Mind sending me a DM on LinkedIn to discuss the next steps: https://www.linkedin.com/in/shubhamsaboo/

**Comment by Madhuvod** [comment]
Changed the readme at the advanced_tools_frameworks/gemini_multimodal_chatbot/README.md

**Comment by Madhuvod** [comment]
Added a new AI Agent Project: AI Health Diet and Fitness Agent with the phidata Framework.

This Streamlit app has 2 files in it: dub.py which is advanced implementation with better Streamlit UI, and health_agent.py which is the basic implementation of the app (useful for beginners).

It has 2 agents - Dietary Agent and Fitness Agent. 

The Image of the same is: 
Screenshot 2024-11-24 at 2 41 37 AM

**Pull request closed without merging**
