### PR TITLE
update all the README.md about how to go to the desired project directory

### PR DESCRIPTION
**Pull request by zjjzyl**
I've found the repository to be incredibly useful.
However, upon walking throught the `ai_customer_support_agent` tutorials, it appears that the README.md files lack instructions on how to navigate to the project directory, which is essential for executing `pip install -r requirements.txt` successfully. 
To resolve this, I'm submitting a pull request to include the missing step.

### CODE REVIEW

**Comment by Madhuvod** [comment]
thanks for your contribution @zjjzyl! if you could spot any other errors in other readme's, add them here so that everything can be merged at the same time

**Comment by Shubhamsaboo** [comment]
Thanks @zjjzyl for the contribution. Merge the changes shortly.

**Comment by alazyer** [comment]
@Madhuvod @Shubhamsaboo Thank you for your fast response, and i will check for the rest of the README.md

**Comment by zjjzyl** [comment]
@Madhuvod  @Shubhamsaboo Thank you for your fast response, and i have updated all the `README.md`, please check it again.

**Comment by Shubhamsaboo** [comment]
@Madhuvod can you please review this for any breaking changes before I merge it?

**Comment by Madhuvod** [comment]
on it

**Comment by Shubhamsaboo** [comment]
@Madhuvod is this good to merge? Have you reviewed it?

**Comment by Madhuvod** [comment]
yes reviewed them, can merge!

**Comment by Shubhamsaboo** [comment]
This branch has some conflicts. Can you please resolve them? @zjjzyl @Madhuvod

**Pull request merged**
