### PR TITLE
Added AI Cooking Assistant

### PR DESCRIPTION
**Pull request by sanketshinde3001**
Title: AI Cooking Assistant

Description:
- meal planning feature that allows users to input available ingredients and dietary preferences.
- used the GEMINI API to generate personalized meal plans and recipes.

[Click here to use](https://ai-cooking.streamlit.app/)

## Screenshot
image

@Shubhamsaboo 
Please let me know your feedback on this !

### CODE REVIEW

**Comment by Shubhamsaboo** [comment]
Hey, I like that its a fully functional app. 

But given the examples, I think it is super simple application that does not show much of strategic thinking.

**Comment by sanketshinde3001** [comment]
@Shubhamsaboo Ohk sir , can you please suggest some complex things that i should add in it. I'm new to this.

**Comment by Shubhamsaboo** [comment]
I’m looking for a project that goes beyond simply using the OpenAI or Anthropic APIs—perhaps something involving advanced agent workflows, RAG systems, or leveraging an open-source framework to achieve unique capabilities like X, Y, or Z.

The project direction would be something I’d rely on you to shape, so I won’t always provide exact instructions or specify each step. I hope that helps clarify my expectations.

**Comment by sanketshinde3001** [comment]
@Shubhamsaboo Ohk sir

**Pull request closed without merging**
